service: birthday-reminder-api

provider:
    name: aws
    runtime: nodejs20.x
    stage: 'dev'
    region: 'eu-west-3'
    memorySize: 128
    timeout: 5
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:Scan
          Resource:
              - arn:aws:dynamodb:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:table/users
              - arn:aws:dynamodb:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:table/birthdays

functions:
    getUserBirthdays: ${file(./src/getUserBirthdays/getUserBirthdays.yml)}
    createNewBirthday: ${file(./src/createNewBirthday/createNewBirthday.yml)}
    updateBirthday: ${file(./src/updateBirthday/updateBirthday.yml)}
    deleteBirthday: ${file(./src/deleteBirthday/deleteBirthday.yml)}
    authorizer: ${file(./src/authorizer/authorizer.yml)}
    verifyOrCreateUser: ${file(./src/verifyOrCreateUser/verifyOrCreateUser.yml)}
