service: birthday-reminder-api

provider:
    name: aws
    runtime: nodejs20.x
    stage: 'dev'
    region: 'eu-west-3'
    memorySize: 128
    timeout: 5

functions:
    getUserBirthdays: ${file(./src/getUserBirthdays/getUserBirthdays.yml)}
    createNewBirthday: ${file(./src/createNewBirthday/createNewBirthday.yml)}
    updateBirthday: ${file(./src/updateBirthday/updateBirthday.yml)}
    deleteBirthday: ${file(./src/deleteBirthday/deleteBirthday.yml)}
    authorizer: ${file(./src/authorizer/authorizer.yml)}
